### ISSUE TITLE
Microsoft Login is grayed out

### ISSUE THREAD

**Issue by SudoTheHacker** [fn2006/PollyMC#102]
### Operating System

Windows 10

### Version of PollyMC

PollyMC 7.2

### Version of Qt

Qt 6.5.2

### Description of bug

When I try to add my microsoft account it's grayed out

### Steps to reproduce

Go to account section and try to add microsoft account

### Suspected cause

Didn't implement it or uses old version of prism

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by fn2006** [comment]
Duplicate of #16.
