### ISSUE TITLE
Make error when building from the AUR

### ISSUE THREAD

**Issue by spxcewolf** [fn2006/PollyMC#108]
### Version of PollyMC

PollyMC 7.2.1

### Version of Qt

Qt 6.6.0

### Description of bug

Trying to build PollyMC from the AUR results in the following error:

```
make[2]: *** [launcher/CMakeFiles/Launcher_logic.dir/build.make:3237: launcher/CMakeFiles/Launcher_logic.dir/translations/TranslationsModel.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2945: launcher/CMakeFiles/Launcher_logic.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

This is a recently closed issue on the PrismLauncher issues page:  PrismLauncher/PrismLauncher#1716
Please pull the required changes from the updated PrismLauncher AUR PKGBUILD.

### Steps to reproduce

Try to build PollyMC from the AUR.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by fn2006** [comment]
Fixed, thanks for making me aware of this.
