### ISSUE TITLE
[Bug] Polly Parrot does not show on Halloween!

### ISSUE THREAD

**Issue by lemonzest79** [fn2006/PollyMC#110]
### Operating System

Fedora Linux 38, AppImage

### Version of PollyMC

PollyMC 7.2

### Version of Qt

Qt 6.2.4

### Description of bug

Polly Parrot background "Cat" does not show from Oct 27th, other "Cat" backgrounds show with Witch Hats/Pumpkins so I'm assuming its some Holiday thing that changes the images and Polly does not have one for this event?

### Steps to reproduce

Select the Polly Parrot background "Cat" Option, Press the Cat button, no image is shown

### Suspected cause

No image available for this Holiday event most likely

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by fn2006** [comment]
Should be fixed in 8.0
