### ISSUE TITLE
Sync with upstream 8.0 release

### ISSUE THREAD

**Issue by felipe19930** [fn2006/PollyMC#115]
Release notes: https://github.com/PrismLauncher/PrismLauncher/releases/tag/8.0

Thank you very much!

**Comment by morganist** [comment]
by the way, prism launcher removed the option to still play with mojang accounts with this version (they say it is no longer possible) so here i am, unable to migrate my account and using this awesome fork that i found out about from an issue in papirus-icon-theme repo... hope this version sync won't bring any problems!

**Comment by fn2006** [comment]
Done, sorry for the wait.
