### ISSUE TITLE
ely.by not working on server even with authlib

### ISSUE THREAD

**Issue by Darklight-007** [fn2006/PollyMC#130]

**Comment by evan-goode** [comment]
Could you please elaborate? Are you using authlib-injector on the server or Ely.by's patched authlib? If you are the one running the server, what is the full command you use to start the server? Is it just that you can't see skins, or can you not log in to the server at all? Can you log in to other Ely.by servers?

**Comment by lemonzest79** [comment]
I run ely.by authlib-injector servers myself, worked perfectly fine when I tested them yesterday (I suffered a machine death, needed to transfer the servers)

**Comment by Darklight-007** [comment]
> Could you please elaborate? Are you using authlib-injector on the server or Ely.by's patched authlib? If you are the one running the server, what is the full command you use to start the server? Is it just that you can't see skins, or can you not log in to the server at all? Can you log in to other Ely.by servers?

i tried using the java argument but diddnt work

**Comment by Darklight-007** [comment]
if yes please tell in detail

**Comment by Darklight-007** [comment]
> Reference

i may not be able to edit the launch arguments
