### ISSUE TITLE
ely.by authlib-injector progress bar stuck

### ISSUE THREAD

**Issue by billlsss** [fn2006/PollyMC#134]
### Operating System

Windows 10

### Version of PollyMC

PollyMC 8.0

### Version of Qt

Qt 6.6.0

### Description of bug

I tried to add my ely.by account through the authlib-injector, but nothing happens. I tried multiple times, restarting the launcher and so on but it doesn't seen to have any effect

![image](https://github.com/fn2006/PollyMC/assets/74934931/a91b912d-e2f6-4db6-b0bd-6e2f800776a1)

It keeps like this and nothing happens

### Steps to reproduce

1- Go to accounts
2- Click on Add authlib-injector
3- Put your ely.by username and password + the API URL
4- Click on OK

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by lemonzest79** [comment]
When copying and pasting the authlib injector url from the wiki make sure the space at the end is deleted and just the url is there, I noticed this today and had to delete a space as the end of the link

**Comment by billlsss** [comment]
> When copying and pasting the authlib injector url from the wiki make sure the space at the end is deleted and just the url is there, I noticed this today and had to delete a space as the end of the link

Oh that solved the problem, thank u so much
