### ISSUE TITLE
Build error with nixos-rebuild switch --flake 

### ISSUE THREAD

**Issue by itslychee** [fn2006/PollyMC#14]
### Operating System

Linux

### Version of PollyMC

da0a7dbbd4803777896cba401f1c4b1c41841f20

### Description of bug

I expected it to build on my system and move on to the next task. My nix configuration does not seem to be causing this problem.

error:
`Cannot wrap '/nix/store/l067ivzp8f51sv9abmj9abz74a6czs3d-polymc-20220728/bin/polymc' because it is not an executable file`

[Full log](https://github.com/fn2006/PollyMC/files/9218878/log.txt)

### Steps to reproduce

- Use nix flakes
- Run `nix flake update` to get the latest flake
- Rebuild your system
- Above should happen

### Suspected cause

https://github.com/PolyMC/PolyMC/pull/893 maybe? Not sure

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by fn2006** [comment]
Ah, this is my fault, when I changed the launcher name to PollyMC I forgot to update the nix stuff, it's failing because it's trying to find a binary called `polymc` when the binary is now called `pollymc`, I'll go update them.

**Comment by itslychee** [comment]
It works now!

**Comment by fn2006** [comment]
Nice!
