### ISSUE TITLE
Build elyby not working

### ISSUE THREAD

**Issue by nisel11** [fn2006/PollyMC#15]
### Operating System

Linux

### Version of PollyMC

PollyMC-1.4.1-elyby

### Description of bug

After entering the command to start the PolyMC build, I got an error: 
***Unknown option --query
CMake Warning at /usr/share/ECM/modules/ECMQueryQt.cmake:97 (message):
  Failed call: "QT_INSTALL_PLUGINS"
Call Stack (most recent call first):
  CMakeLists.txt:191 (ecm_query_qt)

CMake Error at /usr/share/ECM/modules/ECMQueryQt.cmake:98 (message):
  Qt6 qtpaths call failed: 1
Call Stack (most recent call first):
  CMakeLists.txt:191 (ecm_query_qt)

-- Configuring incomplete, errors occurred!

Command: cmake -S . -B build \                                            
           -DCMAKE_INSTALL_PREFIX=install

Please forgive me if I am to blame for the error

### Steps to reproduce

as written in BUILD.MD went to https://polymc.org/wiki/development/build-instructions/ and entered a command in the terminal to build polymc, all dependencies were installed

### Suspected cause

Add ready-made versions of PollyMC with support for ely.by

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by fn2006** [comment]
The elyby branch is experimental and unfinished, please wait until it gets merged into develop.

**Comment by nisel11** [comment]
Thank you
