### ISSUE TITLE
Add Microsoft option grayed out in Account Settings

### ISSUE THREAD

**Issue by KryptoSynth0** [fn2006/PollyMC#16]
### Operating System

Windows

### Version of PollyMC

PollyMC 1.4.1

### Description of bug

Greyed out in PollyMC:
![image](https://user-images.githubusercontent.com/109325672/183285294-aab96b59-1a03-46a9-84ce-fda38c902978.png)

Working in PolyMC:
![image](https://user-images.githubusercontent.com/109325672/183285630-48e945fa-efe8-41ca-91d1-93abdd87462b.png)

### Steps to reproduce

It was like that when I installed the app.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by KryptoSynth0** [comment]
Nevermind, I didn't read the pop-up which says I need to add a Microsoft authentication ID

**Comment by KryptoSynth0** [comment]
How do I get a Microsoft authentication ID?

**Comment by fn2006** [comment]
Why would you even want to use this launcher if you own the game?
To get an MSA token I would have to request one from Microsoft for use with this launcher and there's no way they would give me a token since this launcher breaks the Minecraft EULA.

**Comment by KryptoSynth0** [comment]
Sorry, I just wanted a launcher that allowed me to play both with and without a Microsoft account. I'll just use PolyMC to play online and keep yours as an offline backup then. Thank you for your time.

**Comment by DraconicNEO** [comment]
> Why would you even want to use this launcher if you own the game? To get an MSA token I would have to request one from Microsoft for use with this launcher and there's no way they would give me a token since this launcher breaks the Minecraft EULA.

Why not just harvest the one from PolyMC, that one is valid so it stands to reason that it would work for this, allowing people to use both types of accounts.

**Comment by fn2006** [comment]
> Why not just harvest the one from PolyMC, that one is valid so it stands to reason that it would work for this, allowing people to use both types of accounts.

PolyMC's developers state that you have to accept the terms of use laid down in https://docs.microsoft.com/en-us/legal/microsoft-identity-platform/terms-of-use to use their key, which I do not accept.
Of course there's nothing stopping me from using the key anyway but I respect their wishes and don't want to fuck them over by getting their key revoked so I will not be using it.

**Comment by DraconicNEO** [comment]
> > Why not just harvest the one from PolyMC, that one is valid so it stands to reason that it would work for this, allowing people to use both types of accounts.
> 
> PolyMC's developers state that you have to accept the terms of use laid down in https://docs.microsoft.com/en-us/legal/microsoft-identity-platform/terms-of-use to use their key, which I do not accept. Of course there's nothing stopping me from using the key anyway but I respect their wishes and don't want to fuck them over by getting their key revoked so I will not be using it.

Fair enough.
