### ISSUE TITLE
How to add this GitHub repo as remote using flatpak?

### ISSUE THREAD

**Issue by ukizet** [fn2006/PollyMC#165]
And install using this remote.

**Comment by zocker-160** [comment]
You cannot use a GitHub repo (or any Git repository for that matter) as a remote in Flatpak.

In order to use the flatpak, you either have to use the prebuild package or create it yourself using the manifest available in this the repository.

**Comment by ukizet** [comment]
@zocker-160 what's the point of remotes then, if you can connect only flathub(

**Comment by zocker-160** [comment]
@ukizet this is not true, you can add any remote you want, but the remote has to be a flatpak repository and not a Git repository.

Anyone can host their own flatpak repository and add it as a remote.

It is exactly like all the other Linux package managers work, for example pacman (Archlinux package manager) also needs a pacman repository and cannot pull packages from GitHub.
Anyone can host their own pacman repository though.
