### ISSUE TITLE
Add EasyMC account support

### ISSUE THREAD

**Issue by Imtiyaz0000** [fn2006/PollyMC#183]
### Role

manage minecraft mods easily

### Suggestion

title

### Benefit

join modded mc servers (that require a mojang account).

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

i'm too broke to buy minecraft.
The easymc launcher is pretty bad, so i would like pollymc have easymc authtoken authentication.

**Comment by evan-goode** [comment]
Try making an offline account in PollyMC and then follow the "Mod Download" instructions at the bottom of [this page](https://easymc.io/install). Does that work?

**Comment by Imtiyaz0000** [comment]
> Try making an offline account in PollyMC and then follow the "Mod Download" instructions at the bottom of [this page](https://easymc.io/install). Does that work?

bruh im so dum didn't know there was a forge mod, ty man.
