### ISSUE TITLE
Cannot type or paste token to the CurseForge Core API textbox

### ISSUE THREAD

**Issue by vain05** [fn2006/PollyMC#23]
### Operating System

Arch Linux (5.19.7-arch1-1)

### Version of PollyMC

PollyMC 1.4.1

### Version of Qt

Qt 5.15.5

### Description of bug

After I have build the repo successfully everything works but I cannot type or paste anything to the CurseForge Core API textbox.

### Steps to reproduce

I just complete some basic setup like language, and java path. I then realize that there is no curseforge menu, so I searched for the issue and found that I need to fill the CurseForge API.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by fn2006** [comment]
That's strange, do other dialog boxes work? (Username selection, MSA token box, Useragent, etc)

**Comment by vain05** [comment]
In Services tab, Base URL is not work but the Metadata Server works. In API Keys, the Microsoft Auth works but the CurseForge is not. And the Miscellaneous works.

**Comment by fn2006** [comment]
That's super weird, I noticed you mentioned setting language, is your language set to english in the launcher settings?
If not try setting it to english and trying again, I have a feeling it could be related to what language is being used since I can't reproduce it myself.

**Comment by fn2006** [comment]
I have no idea what's gone wrong then, but yeah you can, in pollymc.cfg there should a line starting with FlameKeyOverride, paste it there.

**Comment by fn2006** [comment]
Oh, I feel dumb now.

**Comment by fn2006** [comment]
Yeah.

**Comment by vain05** [comment]
Thank you a lot :100:
