### ISSUE TITLE
Curseforge API [Need Help]

### ISSUE THREAD

**Issue by DarkStarOnGitHub** [fn2006/PollyMC#26]
Can't figure out how to get the curseforge API key. What utility are is referred to [here](https://github.com/fn2006/PollyMC/wiki/CurseForge-Workaround)?

Can somebody elaborate?

**Comment by TechPro424** [comment]
Also, `chmod` does not exist on Windows, so there's no way for Windows users to get the API key

**Comment by Moouhcine** [comment]
#22 i explained in this how it works

**Comment by TechPro424** [comment]
The CurseForge API key is `$2a$10$bL4bIL5pUWqfcO7KQtnMReakwtfHbNKh6v1uTpKlzhwoueEJQnPnm`

I found it from the 4chan link
Thanks @Moouhcine for the info in #22 
@fn2006 you might want to add this in the wiki directly

**Comment by fn2006** [comment]
I've just improved the instructions and added a script for Windows users.
Also please don't post the API key here, I don't want the repo to get taken down, if I was brave enough to put the key in the wiki entry then I would just skip that step altogether and have the launcher use the key by default.
