### ISSUE TITLE
Can't login with Ely.by account

### ISSUE THREAD

**Issue by spxcewolf** [fn2006/PollyMC#28]
### Operating System

Windows

### Version of PollyMC

PollyMC 1.4.2

### Version of Qt

Qt 6.3.1

### Description of bug

On trying to login with a Ely.by account, a message pops up.
"Minecraft Java profile response could not be parsed"

### Steps to reproduce

Enter account credentials through the "Add Ely.by Account" option and click Ok.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by fn2006** [comment]
The profile will fail to parse if you don't have a skin set, try setting your skin on the Ely.by website and trying again.

**Comment by spxcewolf** [comment]
Thanks, it works now
