### ISSUE TITLE
CurseForge menu not showing modpacks

### ISSUE THREAD

**Issue by marinlovania** [fn2006/PollyMC#3]
### Operating System

Windows 10 64bit

### Version of PolyMC

PolyMC 1.3.1

### Description of bug

Adding instance and going for the CurseForge menu does not show lists of modpacks, instead it's just empty. Any ideas?

### Steps to reproduce

1. Open PolyMC
2. Press "Add Instance"
3. Click CurseForge
4. Nothing shows

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by fn2006** [comment]
CurseForge has started blocking third party clients from downloading mods if they don't have an API key, the official PolyMC has an API key but forks aren't allowed to use it.

A workaround you could use is downloading the mods with the official PolyMC launcher and then launching the instance with this fork.

**Comment by anoraktrend** [comment]
Also: https://git.sakamoto.pl/domi/curseme/-/blob/meow/getToken.sh

**Comment by fn2006** [comment]
Thanks for that utility you linked, just wrote a wiki page that shows people how to use it to workaround this issue.
