### ISSUE TITLE
Curseforge now blocks modirinth workaround

### ISSUE THREAD

**Issue by ComradeWave** [fn2006/PollyMC#31]
### Operating System

Windows

### Version of PollyMC

PollyMC 1.4.1

### Version of Qt

Qt 6.3.0

### Description of bug

When the Modirinth workaround is applied in the miscellaneous tab, even if the CurseForge API is inserted, it will stop working. 

### Steps to reproduce

Insert the Curseforge API
Change the miscellaneous tab to `PolyMC/$LAUNCHER_VER`
Curseforge page stops working

### Suspected cause

Probably curseforge blocked PolyMC due to what's happening. To fix it, just replace `PolyMC/$LAUNCHER_VER` to `UltiMC/$LAUNCHER_VER`,  updating the wiki should be enough

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by fn2006** [comment]
Thanks for bringing this to my attention, fixed.
