### ISSUE TITLE
Hotfix Still Doesn't Work In Windows

### ISSUE THREAD

**Issue by HuggedJacker** [fn2006/PollyMC#34]
### Operating System

Windows

### Version of PollyMC

PollyMC 5.1-hotfix

### Version of Qt

I Can't Open PollyMC to find that.

### Description of bug

The hotfix doesn't seem to fix the issue for me. FYI I am using The portable windows version on the latest Windows version.
Maybe you should check the windows version again.
![explorer_eJUpjfuuaW](https://user-images.githubusercontent.com/89655926/199494610-146667d6-c3fb-454a-9096-4d91ccdd3526.png)
#33 Also Has this so try to look into it.

### Steps to reproduce

Launch PollyMC 5.1-hotfix

### Suspected cause

=================
Begin Activation Context Generation.
Input Parameter:
	Flags = 0
	ProcessorArchitecture = AMD64
	CultureFallBacks = en-US;en
	ManifestPath = C:\Users\furqa\Downloads\Compressed\pollymc.exe
	AssemblyDirectory = C:\Users\furqa\Downloads\Compressed\
	Application Config File = 
-----------------
INFO: Parsing Manifest File C:\Users\furqa\Downloads\Compressed\pollymc.exe.
	INFO: Manifest Definition Identity is (null).
	ERROR: Line 3: The value  of attribute version in element assemblyIdentity is invalid.
ERROR: Activation Context generation failed.
End Activation Context Generation.

### This issue is unique

- [ ] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by fn2006** [comment]
Sorry I was busy with something else and didn't respond sooner, the hotfix worked on wine so I assumed it would also fix the issue on Windows, I'll test https://github.com/fn2006/PollyMC/pull/36 and merge it if it works.

**Comment by HuggedJacker** [comment]
Great! thanks for the response.

**Comment by fn2006** [comment]
Should be fixed.
