### ISSUE TITLE
The program is shut down

### ISSUE THREAD

**Issue by Ka1dz0** [fn2006/PollyMC#37]
### Operating System

Windows

### Version of PollyMC

PollyMC 5.1

### Version of Qt

Qt 6.4.0

### Description of bug

When you try to install a modpack from the Archive or ATLauncher program instantly closes without errors

### Steps to reproduce

Restarting the program and the system, trying to install modpack from the archive

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by fn2006** [comment]
Downloading ATLauncher packs crashing the launcher on Windows is a known bug upstream (https://github.com/PrismLauncher/PrismLauncher/issues/376).
When you say archive you mean importing from a zip right? if so what sort of modpack are you trying to import?

**Comment by Ka1dz0** [comment]
> Downloading ATLauncher packs crashing the launcher on Windows is a known bug upstream ([PrismLauncher/PrismLauncher#376](https://github.com/PrismLauncher/PrismLauncher/issues/376)). When you say archive you mean importing from a zip right? if so what sort of modpack are you trying to import?

_Problem solved the same day, forgot to sign off here)
The problem corrected by adding CurseForge API in the launcher, after that crashes were not._

**Comment by fn2006** [comment]
The ATLauncher crash is fixed in 5.2
