### ISSUE TITLE
Curseforge mods not working

### ISSUE THREAD

**Issue by slosa** [fn2006/PollyMC#39]
### Operating System

Linux

### Version of PollyMC

PollyMC 5.2

### Version of Qt

Qt 5.15.6

### Description of bug

i wanted to add mods via curseforge, but i cant write or paste into the text field, nothing happens, occurs only in this text field

### Steps to reproduce

try to paste the curseforge token onto the curseforge text field

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by slosa** [comment]
> Make sure there's no spaces in front of or after the key, the text field works but it only accepts valid input.

ok, thanks, but i dont see the curseforge mods / packs do i have to enable something else

**Comment by fn2006** [comment]
They should show up once you put the key in, try restarting the launcher.

**Comment by slosa** [comment]
> They should show up once you put the key in, try restarting the launcher.
yea i put accidentally typed one char onto the token, thanks though

i wanted to ask if you would be willing to add custom minecraft jar + json support, i know multimc doesnt support it, but do you think the prism team are planning to add it?

**Comment by fn2006** [comment]
> i wanted to ask if you would be willing to add custom minecraft jar + json support, i know multimc doesnt support it, but do you think the prism team are planning to add it?

I'm not the right person to ask about that, you should open an issue in Prism's repo asking for custom minecraft jar + json support

**Comment by slosa** [comment]
> > i wanted to ask if you would be willing to add custom minecraft jar + json support, i know multimc doesnt support it, but do you think the prism team are planning to add it?
> 
> I'm not the right person to ask about that, you should open an issue in Prism's repo asking for custom minecraft jar + json support

okay thanks anyway, but i think they will say know cause mojang doesnt reccommend doing that, and cause this launcher already has something that "doesnt allow" i thoughts you were maybe thinking about it, ok thanks ima ask there

**Comment by fn2006** [comment]
I don't think they'll say no just because Mojang doesn't recommend it, it's not against Minecraft's terms of service and it's useful in some cases.
Also can I close this?

**Comment by slosa** [comment]
> I don't think they'll say no just because Mojang doesn't recommend it, it's not against Minecraft's terms of service and it's useful in some cases. Also can I close this?

yea you can, as predicted they said no :(, they say that it breaks eula, if i distribute it but what if wont, sad thats only bad thing about that, i know basics of c, how hard would be implementing that to the prism laucnher?, i would make pull request if i managed to do it

**Comment by fn2006** [comment]
Sorry, I was busy with something else and didn't see your reply till just now.
I just reread the EULA and they're right, although technically while the mods themselves break the EULA, having support for them doesn't.

> how hard would be implementing that to the prism laucnher?

I'm honestly not sure, I've not really looked at that area of the source code.

Anyway I'm going to close this now since your issue with the curseforge mods is fixed, I'll take a look at custom jar support but no promises, I thought the "Replace Minecraft.jar" button in the instance settings was custom jar support tbh.

**Comment by slosa** [comment]
yea i made it work but it only works if the client doesnt have custom json with its own libs
