### ISSUE TITLE
Can you fork GDlauncher the same way?

### ISSUE THREAD

**Issue by HuggedJacker** [fn2006/PollyMC#40]
### Role

I mostly play modded minecraft.

### Suggestion

I want you to fork GDlauncher the same way as Prismlauncher.

### Benefit

Auto-updating modpacks, better UI imo, more user-friendly, we can add multiple Java.exe to not worry about changing java installation again and much more.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by HuggedJacker** [comment]
Yk just a suggestion.

**Comment by fn2006** [comment]
Sorry, I don't have any interest in this but a quick glance at https://github.com/gorilla-devs/GDLauncher/network/members shows multiple forks with similar features to this fork.
