### ISSUE TITLE
README.md: Incorrect.

### ISSUE THREAD

**Issue by EndlessEden** [fn2006/PollyMC#42]
### Version of PollyMC

Pollymc-xxxx

### Version of Qt

xxx

### Description of bug

Pollymc is a Fork of MultiMC, NOT Prism Launcher;

Prism Launcher solely exists /because/ Pollymc takeover. | Please read (https://github.com/PolyMC/PolyMC/commit/ab3e2562db52d66f690f08621e220766b0953af7) to review the timeperiod of when the fork-split occurred.

### Steps to reproduce

1. open https://github.com/fn2006/PollyMC
2. Be presented with incorrect/false information.

### Suspected cause

Misread or earlier (falsehood) edit by pollymc/pollymc

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by offbeat-stuff** [comment]
Wrong repo bro, wrong repo

**Comment by offbeat-stuff** [comment]
okay look bro, I check the bro that made the repo bro, he cant change the upstream url bro, So its going to look like fork of PolyMc bro
Ok bro chill out, we know what we are getting into bro

**Comment by offbeat-stuff** [comment]
now that I look at your profile, maybe I should not have used bro

**Comment by offbeat-stuff** [comment]
also can you please can Pollymc to Polymc where its refering to Polymc (that original one) cause its kinda confusing when you say Pollymc/Pollymc if it is referring to Polymc/Polymc or fn2006/PollyMc

**Comment by thewackymoon** [comment]
This issue should be closed already - there's no mistake in readme.md. PollyMC (with a double L) was initially a fork of PolyMC, then switched to Prism Launcher codebase after PolyMC got into shady stuff.

**Comment by EndlessEden** [comment]
I believe you are correct, and i misread. Sorry - Guess thats what i get for filing a issue at 3am.

**Comment by fn2006** [comment]
Oh sorry I didn't mean to ghost you, I thought I had already responded to this.
