### ISSUE TITLE
Invalid Session error when playing LAN with Offline accounts

### ISSUE THREAD

**Issue by imsamuka** [fn2006/PollyMC#44]
### Operating System

Linux

### Version of PollyMC

PollyMC 6.0

### Version of Qt

Qt 6.4.1

### Description of bug

Can't connect to a 1.7.10 LAN server. It gives this message: 

![connection error message](https://i.imgur.com/uM83o8k.png)

### Steps to reproduce

1. Create a (1.7.10) instance.
2. Run to download libraries.
3. Close and copy the instance.
4. Run both instances at once with 2 different accounts.
5. Create a world in one of the open games.
6. Start a LAN server.
7. Try to connect to the LAN server using the other game.

### Suspected cause

I tried and i can connect fine using PolyMC 1.4.3 (the aur cracked version, that was apparently removed). So the problem was probably introduced on PrismLauncher or PollyMC. 

Relevant logs: 

```
...
[20:13:56] [Client thread/INFO]: Started on 41401
[20:13:56] [Client thread/INFO]: [CHAT] Local game hosted on port 41401
[20:14:05] [Server thread/INFO]: com.mojang.authlib.GameProfile@6b44a2cf[id=<null>,name=imsamuka2,properties={},legacy=false] (/127.0.0.1:48198) lost connection: Disconnected
```

Also, by opening the server on a PolyMC (1.4.3) instance, and trying to connect using PollyMC, the log is the same.

But by doing the inverse, open the server on PollyMC, and using a PolyMC to connect, the connection works fine.

I couldn't test in the Prismlauncher, since i don't own a account yet; So i posted the issue here...

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by fn2006** [comment]
What account type are you using?
I'm going to bed now but I'll take a look at this when I have time tomorrow.

**Comment by imsamuka** [comment]
Offline account.

**Comment by imsamuka** [comment]
I got a friend of mine to test this on PrismLauncher. It works fine, so it's really a PollyMC issue.

**Comment by ComradeWave** [comment]
@imsamuka What version of Java are you using? I think there might be connectivity issues in some Java versions compatible with 1.7.10, you could try [this version of Java](https://www.oracle.com/it/java/technologies/javase/javase7-archive-downloads.html).

**Comment by imsamuka** [comment]
Java 1.8.0_352

But how could this be the issue? Since both instances are running the same version of Java?

**Comment by fn2006** [comment]
Sorry I took a while to get back to you, I've done some testing myself and I can reproduce the issue.

What I've found is that offline accounts can't join each others LAN games but they can join `online-mode=false` servers, interestingly microsoft accounts can join offline accounts' LAN games but offline accounts can't join microsoft accounts' LAN games.

What's even stranger is I remember this used to work fine but I downloaded an older version of Polly but it gave me the same invalid session error.

I'll keep digging and try to figure out how to fix this.
> What "Microsoft account on offline mode" have that "Offline account" doesn't?

I think this will probably be a big clue in fixing it.

**Comment by imsamuka** [comment]
> older version of Polly

@fn2006 Maybe we can pinpoint the issue with git bisect then?

**Comment by fn2006** [comment]
Nah, it turns out I was misremembering and offline account LAN never worked, me and my friend were actually using ely.by accounts on LAN.

**Comment by fn2006** [comment]
Alright, I've found the problem but I'm not sure how to go about fixing it.
1.7.7 started enforcing online-mode=true for LAN games, if you try to play LAN with offline accounts on 1.7.6 or older then it works perfectly.

Personally I would just use ely.by accounts.

**Comment by imsamuka** [comment]
I see, using https://www.curseforge.com/minecraft/mc-mods/server-properties-for-lan and enforcing `online-mode=false` solves the problem too. But how can Microsoft accounts Offline work?

**Comment by fn2006** [comment]
I'm not sure, the launcher doesn't seem to handle microsoft accounts in offline mode that differently to offline mode accounts so I'd guess that even though the username's been changed everything else is still valid so the game lets it in.

**Comment by imsamuka** [comment]
What you mean by *everything else*? There's any way to mimick it?

**Comment by fn2006** [comment]
I mean things like the UUID, access token, etc. 
Since `online-mode=true` means that everything is verified on Mojang's servers it's impossible to fool by sending fake data that's in the right format.

**Comment by imsamuka** [comment]
I see. So I assume that the only workaround is a mod on the Host game, or using versions before 1.7.6 then.

**Comment by yum13241** [comment]
I remember back when I was 9 or smth, using TLauncher (ik it's a virus now) on 1.12.2 and it worked fine. (might be irrelevant)


On PollyMC, I can join 2 Ely.by accounts or a mix and match. The host always used an Ely.by account. I was using modded 1.12.2. Both machines were on Linux and use the `pollymc-bin` package from the AUR.

**Comment by LegendaryGW** [comment]
The mod linked earlier in this thread seems to have its latest version for 1.12.2. I was able to find another mod for later versions
(https://www.curseforge.com/minecraft/mc-mods/lan-server-properties)
However, when I tried LAN with online mode turned off, it still gave me the same invalid session error.
So is the only fix for now to use ely.by accounts?

**Comment by MIOGMIOG** [comment]
> I remember back when I was 9 or smth, using TLauncher (ik it's a virus now) on 1.12.2 and it worked fine. (might be irrelevant)
> 
> On PollyMC, I can join 2 Ely.by accounts or a mix and match. The host always used an Ely.by account. I was using modded 1.12.2. Both machines were on Linux and use the `pollymc-bin` package from the AUR.

thats because tlauncher launches game in offline mode, but IIRC pollymc emulates auth server

**Comment by yum13241** [comment]
PollyMC should only be *redirecting* the game to Ely.by auth servers with an ely.by account. It shouldn't be doing what UltimMC does.

**Comment by Hexality** [comment]
![image](https://github.com/fn2006/PollyMC/assets/17398632/9bf61a60-9971-4614-989b-efb44ee91def)

**Comment by evan-goode** [comment]
@Hexality that seems to be https://github.com/fn2006/PollyMC/issues/63

**Comment by offbeat-stuff** [comment]
fabric mc seems to working on fix for 1.16.5 on their dev environments.

**Comment by offbeat-stuff** [comment]
https://github.com/FabricMC/fabric-loom/issues/915

**Comment by offbeat-stuff** [comment]
So the only way to fix this issue is to make accounts on a alternative server, gotcha

**Comment by Darukutsu** [comment]
https://github.com/satxm/mcwifipnp this fixes it for me
