### ISSUE TITLE
Can't play beta with my ely.by account

### ISSUE THREAD

**Issue by ArmolitskiyCarpoeb** [fn2006/PollyMC#45]
### Operating System

Windows

### Version of PollyMC

6.0

### Version of Qt

Qt 6.4.0

### Description of bug

[authlib-injector] [INFO] Logging file: C:\Users\admin\AppData\Roaming\PollyMC\instances\BTA_1.7.6.2_02\.minecraft\authlib-injector.log 
[authlib-injector] [INFO] Version: 1.2.1 
[authlib-injector] [INFO] Authentication server: https://ely.by 
[authlib-injector] [ERROR] Failed to fetch metadata: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target 
Процесс завершился с кодом 1.

### Steps to reproduce

Launch the instance with ely.by account

### Suspected cause

IDK!

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by ArmolitskiyCarpoeb** [comment]
https://mclo.gs/gWFw0PN

**Comment by ArmolitskiyCarpoeb** [comment]
The problem is beta 1.7.3 or BTA mod

**Comment by fn2006** [comment]
According to your logs you're using a really old version of Java 8, that might be the problem.
I've just tested both b1.7.3 and BTA and I can play them with an ely.by account (skin doesn't work but the game launches fine).

**Comment by ArmolitskiyCarpoeb** [comment]
> According to your logs you're using a really old version of Java 8, that might be the problem, try using the latest [Temurin](https://adoptium.net/temurin/releases/?version=8) build.
> 
> I've just tested both b1.7.3 and BTA and I can play them with an ely.by account (skin doesn't work but the game launches fine).


THANKS, FIXED
