### ISSUE TITLE
Ely.by user authentication ended with a network error

### ISSUE THREAD

**Issue by thewackymoon** [fn2006/PollyMC#46]
### Operating System

Windows

### Version of PollyMC

PollyMC 6.0

### Version of Qt

Qt 6.4.1

### Description of bug

After entering valid Ely.by login credentials, the launcher shows the following error message
![изображение](https://user-images.githubusercontent.com/98486143/208281299-bc9a9ef8-ebe6-4620-84b8-ef471b5956ac.png)

### Steps to reproduce

1. Open PollyMC
2. Go to **Settings**
3. Go to **Accounts**
4. Click **Add Ely.by**
5. Enter Ely.by credentials and click OK

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by CrystallizedShadow** [comment]
Seems like the SSL certificate has expired
`21.425 D AuthFlow: "Logging in with Ely.by account."
   21.425 D Task "Yggdrasil(0x556361c31f60)" starting for the first time
   23.289 C LOGIN SSL Error # 1  :  "The certificate has expired"
   23.290 C Certificate in question:
 "Certificate:\n    Data:\n        Version: 3 (0x2)\n        Serial Number:\n            c9:c6:18:7c:6c:9a:fc:2c:df:9a:9e:8c:7f:1a:71:8f\n        Signature Algorithm: sha256WithRSAEncryption\n        Issuer: C=GB, ST=Greater Manchester, L=Salford, O=Sectigo Limited, CN=Sectigo RSA Domain Validation Secure Server CA\n        Validity\n            Not Before: Nov 17 00:00:00 2021 GMT\n            Not After : Dec 17 23:59:59 2022 GMT\n        Subject: CN=authserver.ely.by\n        Subject Public Key Info:\n            Public Key Algorithm: rsaEncryption\n                Public-Key: (2048 bit)\n                Modulus:\n                    00:ca:0c:8a:aa:53:48:76:6f:72:b0:c1:81:72:a5:\n                    e8:2a:5c:8c:19:ce:21:2a:5b:b2:13:1f:a8:c2:04:\n                    e5:d2:e4:f7:86:f8:79:dc:91:08:27:23:4f:10:55:\n                    bc:d9:e2:bb:68:d5:5a:62:05:f3:51:bc:50:be:f6:\n                    f4:ff:67:c8:b6:ab:b3:6c:9c:60:d6:73:7e:ce:7c:\n                    8a:c7:bb:43:66:74:b5:06:49:25:f8:20:a9:ea:bd:\n                    8b:f5:c9:8e:81:ab:a9:39:55:e1:b1:b0:d9:b8:02:\n                    e9:2d:6c:f5:11:01:b0:ec:9e:77:b3:da:51:bc:01:\n                    39:7e:63:1f:4b:de:04:dc:03:6d:6d:6a:67:92:53:\n                    b4:a4:3b:6d:fa:72:67:fb:fd:6e:3a:b1:6b:6f:3d:\n                    b0:28:af:0e:77:d0:aa:8e:3d:99:75:21:ca:98:ef:\n                    af:24:a4:fa:a0:a4:e4:91:dd:89:29:a4:5d:de:80:\n                    0e:1f:40:f9:af:2a:ee:0e:95:4e:39:13:9f:e1:68:\n                    c5:e9:73:9d:28:25:6e:b6:55:68:bc:79:78:84:25:\n                    f6:f5:5f:cd:6d:b0:65:91:a8:d9:08:f7:d7:c7:a2:\n                    bc:14:4b:4f:56:d4:35:89:00:89:1e:57:e2:c6:c3:\n                    e6:f7:a3:c7:25:cd:1d:6b:1f:1b:45:1c:2a:a4:40:\n                    40:15\n                Exponent: 65537 (0x10001)\n        X509v3 extensions:\n            X509v3 Authority Key Identifier: \n                8D:8C:5E:C4:54:AD:8A:E1:77:E9:9B:F9:9B:05:E1:B8:01:8D:61:E1\n            X509v3 Subject Key Identifier: \n                3E:8F:D9:20:01:8D:0D:21:F0:11:F5:82:69:EB:15:36:B7:EC:CB:27\n            X509v3 Key Usage: critical\n                Digital Signature, Key Encipherment\n            X509v3 Basic Constraints: critical\n                CA:FALSE\n            X509v3 Extended Key Usage: \n                TLS Web Server Authentication, TLS Web Client Authentication\n            X509v3 Certificate Policies: \n                Policy: 1.3.6.1.4.1.6449.1.2.2.7\n                  CPS: https://sectigo.com/CPS\n                Policy: 2.23.140.1.2.1\n            Authority Information Access: \n                CA Issuers - URI:http://crt.sectigo.com/SectigoRSADomainValidationSecureServerCA.crt\n                OCSP - URI:http://ocsp.sectigo.com\n            X509v3 Subject Alternative Name: \n                DNS:authserver.ely.by, DNS:www.authserver.ely.by\n            CT Precertificate SCTs: \n                Signed Certificate Timestamp:\n                    Version   : v1 (0x0)\n                    Log ID    : 46:A5:55:EB:75:FA:91:20:30:B5:A2:89:69:F4:F3:7D:\n                                11:2C:41:74:BE:FD:49:B8:85:AB:F2:FC:70:FE:6D:47\n                    Timestamp : Nov 17 01:07:19.496 2021 GMT\n                    Extensions: none\n                    Signature : ecdsa-with-SHA256\n                                30:45:02:20:3D:32:4F:8B:5A:E0:48:C4:CA:4C:11:B5:\n                                95:01:64:6E:56:53:F9:16:85:1C:ED:36:FC:26:C9:9B:\n                                51:CC:25:80:02:21:00:E5:88:21:59:20:6E:BD:AD:99:\n                                DB:E0:36:E8:6F:6E:1D:46:C0:5C:2C:1E:EF:1A:BD:0A:\n                                1D:54:A4:EF:3B:BB:CE\n                Signed Certificate Timestamp:\n                    Version   : v1 (0x0)\n                    Log ID    : 41:C8:CA:B1:DF:22:46:4A:10:C6:A1:3A:09:42:87:5E:\n                                4E:31:8B:1B:03:EB:EB:4B:C7:68:F0:90:62:96:06:F6\n                    Timestamp : Nov 17 01:07:19.430 2021 GMT\n                    Extensions: none\n                    Signature : ecdsa-with-SHA256\n                                30:45:02:21:00:CB:82:43:CC:35:92:15:29:3F:AF:C1:\n                                77:AB:3F:81:90:3B:57:BD:B4:B1:BB:5E:B3:38:25:4E:\n                                4A:C6:58:EF:A7:02:20:62:0D:DD:89:7A:E6:89:77:42:\n                                2C:89:93:CC:40:36:48:CF:4B:40:17:F1:ED:57:51:FD:\n                                0C:39:C5:C9:49:2C:CC\n                Signed Certificate Timestamp:\n                    Version   : v1 (0x0)\n                    Log ID    : 29:79:BE:F0:9E:39:39:21:F0:56:73:9F:63:A5:77:E5:\n                                BE:57:7D:9C:60:0A:F8:F9:4D:5D:26:5C:25:5D:C7:84\n                    Timestamp : Nov 17 01:07:19.383 2021 GMT\n                    Extensions: none\n                    Signature : ecdsa-with-SHA256\n                                30:43:02:1F:1A:D6:98:F3:DB:32:A2:C9:12:CC:DD:F8:\n                                7C:C9:D8:4A:49:76:9E:5B:1A:9A:6C:8B:0E:A8:EC:7A:\n                                BD:EB:6C:02:20:37:41:CE:FE:F6:72:91:F6:6B:F5:85:\n                                86:16:F8:02:A8:2D:8B:85:37:8C:AF:5F:8C:0A:EB:21:\n                                08:9D:E0:79:28\n    Signature Algorithm: sha256WithRSAEncryption\n    Signature Value:\n        9e:ec:80:89:24:30:38:ef:f8:b0:ce:fb:07:62:ec:08:77:9e:\n        9c:1c:81:64:23:e0:3b:26:f3:f6:88:53:e9:12:9b:d8:1a:f3:\n        ce:0e:e9:3e:39:4e:8f:df:10:3f:93:94:5e:d8:2e:f8:cb:74:\n        71:56:01:71:48:8f:db:cc:3d:ab:0e:b2:d9:9b:45:75:b5:01:\n        a9:66:c5:a8:71:61:f1:6f:29:45:ed:68:2f:6a:c4:c7:95:4b:\n        96:6b:7c:af:2b:43:91:95:17:1b:dd:83:ae:df:a3:d5:ef:0c:\n        60:d3:4c:b9:6e:45:81:10:f6:f8:0b:a6:44:4b:5f:25:58:4e:\n        45:92:2b:ba:10:ec:11:2f:56:a5:51:b0:22:74:dc:a3:ed:3f:\n        6e:b3:fb:ed:c8:83:6d:1c:ae:76:9b:0d:d7:e2:98:5e:54:7f:\n        a5:b2:7b:9b:da:69:78:b7:91:3e:2f:1c:a5:67:e2:c1:e1:ef:\n        5a:0b:f7:54:c1:21:33:53:04:00:58:33:36:8d:d0:70:0f:f8:\n        46:bd:5a:d2:f8:80:cd:5b:a4:fe:09:fd:63:52:c1:ac:62:ea:\n        0c:ae:c9:fc:d2:78:6b:5a:ac:47:f5:f6:9f:c4:b0:1d:ed:18:\n        61:8e:46:2e:50:e2:a5:40:5f:ae:86:77:7d:ee:3a:00:c0:d3:\n        a7:e6:24:0a\n"
   23.290 C Task "Yggdrasil(0x556361c31f60)" failed:  "<b>SSL Handshake failed.</b><br/>There might be a few causes for it:<br/><ul><li>You use Windows and need to update your root certificates, please install any outstanding updates.</li><li>Some device on your network is interfering with SSL traffic. In that case, you have bigger worries than Minecraft not starting.</li><li>Possibly something else. Check the log file for details</li></ul>"
   23.290 C Task "ElybyLogin(0x556361cc5a60)" failed:  "Ely.by user authentication ended with a network error."
   30.432 D [HttpMetaCache] Saving metacache with 21 entries`

**Comment by thewackymoon** [comment]
So, an SSL sertificate in the launcher itself got expired and now it fails to do SSL handshake with Ely.by services?

**Comment by lemonzest79** [comment]
My Ely.by account added months ago shows "Offline" in the accounts page of PollyMC also so can also confirm

**Comment by lemonzest79** [comment]
After posting the issue to the ely.by accounts github they have issued a temp fix, PollyMC now says "Ready" for the account status and my own personal server that is ely.by authed works too.

**Comment by thewackymoon** [comment]
> After posting the issue to the ely.by accounts github they have issued a temp fix, PollyMC now says "Ready" for the account status and my own personal server that is ely.by authed works too.

Yeah, that was a Ely.by issue, not PollyMC issue. Closing now
