### ISSUE TITLE
About Parrot

### ISSUE THREAD

**Issue by ripsivis** [fn2006/PollyMC#49]
### Operating System

Linux

### Version of PollyMC

PollyMC 6.1

### Version of Qt

Qt 5.15.7+kde+r177

### Description of bug

The parrot button should show a parrot, but it cannot!

![Screenshot_20221224_232143](https://user-images.githubusercontent.com/57156687/209450208-305deb2a-a508-4252-92d6-229cb53931d3.png)

![Screenshot_20221224_232128](https://user-images.githubusercontent.com/57156687/209450211-24fea9cb-48c8-4e8a-acd8-06ad87412a0d.png)

### Steps to reproduce

* Change the value for parrot button to Polly Parrot and press the parrot button.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by fn2006** [comment]
This broke when Prism introduced their new cat/background system, I was too lazy to fix it because I thought nobody would notice but I've been caught, I'll fix it soon.

**Comment by fn2006** [comment]
Fixed in https://github.com/fn2006/PollyMC/commit/1ff4c683b26141833d26e7d20af774fed252f260, you can get a debug build from the actions section if you really want to see the parrot and can't wait till the next release.

**Comment by ripsivis** [comment]
> This broke when Prism introduced their new cat/background system, I was too lazy to fix it because I thought nobody would notice but I've been caught, I'll fix it soon.

And I was too lazy to report this weeks ago lmao
