### ISSUE TITLE
Bug: Impossible to add ely.by account protected by 2FA

### ISSUE THREAD

**Issue by lemonzest79** [fn2006/PollyMC#54]
### Version of PollyMC

PollyMC 6.3

### Version of Qt

Qt 6.2.4

### Description of bug

Impossible to add an Ely.by account protected by 2FA

### Steps to reproduce

Enable 2FA on the Ely.by account and when attempting to log in with it results in a 204 log in error and it can not be added

### Suspected cause

2FA not being a supported log in method

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by lemonzest79** [comment]
After reading the doc here https://docs.ely.by/en/minecraft-auth.html I could log if if I did "password:number" from the 2FA App (Authy) seems easy enough to request the token from the user and append it to the password??

**Comment by fn2006** [comment]
Closed by 392822ec7aab149e965842f2701d37b1ab643d3b
Sorry it took me a while to do this despite it being a very simple addition, I haven't had much free time till very recently.
