### ISSUE TITLE
Crash with an authlib injector error on curseforge modded instances

### ISSUE THREAD

**Issue by NeidGood13** [fn2006/PollyMC#57]
### Operating System

Windows

### Version of PollyMC

6.3

### Version of Qt

6.4.2.

### Description of bug

modded minecraft crashes on launch with this error in the log

[authlib-injector] [INFO] Logging file: C:\Users\Crimson\AppData\Roaming\PollyMC\instances\DarkRPG - RPG Quest Magic & Origins\minecraft\authlib-injector.log
[authlib-injector] [INFO] Version: 1.2.2
[authlib-injector] [INFO] Authentication server: https://ely.by
[authlib-injector] [ERROR] Failed to fetch metadata: java.net.ConnectException: Connection timed out: connect
Process exited with code 1.

### Steps to reproduce

launch a modded instance, for me it was curseforge darkpg modpack

### Suspected cause

something to do with authlib injector? idk

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by lemonzest79** [comment]
I just connected fine to my 3 Modded servers, it also showed that it used authlib-injector 1.2.2

**Comment by NeidGood13** [comment]
> I just connected fine to my 3 Modded servers, it also showed that it used authlib-injector 1.2.2
did you use a ely.by account?

**Comment by NeidGood13** [comment]
> I just connected fine to my 3 Modded servers, it also showed that it used authlib-injector 1.2.2

have you used a ely.by account?

**Comment by lemonzest79** [comment]
> > I just connected fine to my 3 Modded servers, it also showed that it used authlib-injector 1.2.2
> 
> have you used a ely.by account?

Of course I have :)

**Comment by lemonzest79** [comment]
How long have you had this ely.by account? I read somewhere that you need to select a skin or it can give errors when connecting

**Comment by NeidGood13** [comment]
i think i created it 2 days ago, i selected a skin but everything is the same, just crashes on launch. Was these modded servers from curseforge? I think the problem is with curseforge, because something like BTA or modrinth modpacks work just fine

**Comment by lemonzest79** [comment]
I downloaded the Dark RPG mod and it works fine for me

![2023-03-30_19 10 36](https://user-images.githubusercontent.com/40669977/228927102-b617ce7e-af94-40fa-80fd-fdbec13d74d5.png)
![2023-03-30_19 10 02](https://user-images.githubusercontent.com/40669977/228927122-3fb0f45d-73f1-40ab-a145-47fbc57992ff.png)

**Comment by NeidGood13** [comment]
okay i just installed adoptium java and now everything works fine 💀
