### ISSUE TITLE
AUR fails to build

### ISSUE THREAD

**Issue by Orest58008** [fn2006/PollyMC#59]
### Version of PollyMC

PollyMC 6.3-1

### Version of Qt

Qt 6.5.0-3

### Description of bug

`pollymc` package fails to build:

```
[0.011s][warning][cds] A jar file is not the one used while building the shared archive file: /usr/lib/jvm/java-20-openjdk/lib/modules
[0.011s][warning][cds] /usr/lib/jvm/java-20-openjdk/lib/modules timestamp has changed.
warning: [options] bootstrap class path not set in conjunction with -source 7
error: Source option 7 is no longer supported. Use 8 or later.
error: Target option 7 is no longer supported. Use 8 or later.
make[2]: *** [libraries/launcher/CMakeFiles/NewLaunch.dir/build.make:96: libraries/launcher/CMakeFiles/NewLaunch.dir/java_compiled_NewLaunch] Помилка 2
make[1]: *** [CMakeFiles/Makefile2:1382: libraries/launcher/CMakeFiles/NewLaunch.dir/all] Помилка 2
make: *** [Makefile:146: all] Помилка 2
==> ПОМИЛКА: Стався збій у build().
    Припинення...
error: failed to build 'pollymc-6.3-1':
error: packages failed to build: pollymc-6.3-1
```

### Steps to reproduce

Install PollyMC through the Arch User Repository. Fails both when installing using AUR helper(I used paru) and makepkg.
Installing `pollymc-qt5` yields the same issue.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by fn2006** [comment]
I notice your logs show you're using Java 20, please could you try with Java 17?
If it still doesn't work I'll take a look at it later today.

**Comment by Orest58008** [comment]
Thanks, that solved the issue
