### ISSUE TITLE
Skins failing to upload

### ISSUE THREAD

**Issue by FarloxStudios** [fn2006/PollyMC#6]
### Operating System

Windows

### Version of PolyMC

PolyMC 1.3.2

### Description of bug

Failed to Upload skin

### Steps to reproduce

Go manage accounts, user account and upload skin.

### Suspected cause

no skin support for offline?

**Comment by fn2006** [comment]
Sorry, there isn't any support for offline skins atm, the upload skin button not being greyed out for offline accounts is a bug that's fixed in 1.4.0.
I'm going to leave this open though because I plan to add ely.by support at some point.

**Comment by FarloxStudios** [comment]
pogchamp
btw tysm for pollymc fr just found it today been using the shitty
sklauncher and i finally dont got to lag when i open a launcher for
modpacks

**Comment by fn2006** [comment]
Added support for Ely.by accounts in 5a611c6ffc24fa2e48ec6adff158a2a560a63e19, they don't seem to have an API for changing skins though so you'll have to use their website instead of this launcher to change skins.
