### ISSUE TITLE
Cannot run PollyMC 7.0 [AUR pollymc-bin build]

### ISSUE THREAD

**Issue by spxcewolf** [fn2006/PollyMC#68]
### Operating System

Linux

### Version of PollyMC

PollyMC 7.0 (pollymc-bin on the AUR)

### Version of Qt

Qt 6.5.1-2

### Description of bug

Cannot launch the application. Trying to launch it from the terminal results in this error:
```
warning: direct reference to protected function '_ZNK19QStyledItemDelegate15initStyleOptionEP20QStyleOptionViewItemRK11QModelIndex' in '/usr/lib/libQt6Widgets.so.6' may break pointer equality
pollymc: _ZNK19QStyledItemDelegate15initStyleOptionEP20QStyleOptionViewItemRK11QModelIndex: /usr/lib/libQt6Widgets.so.6: error due to GNU_PROPERTY_1_NEEDED_INDIRECT_EXTERN_ACCESS
```

### Steps to reproduce

Run it through the terminal. (This was done just to get the error message)

[Operating System : Arch Linux]

### Suspected cause

Seems to be a problem with one of the Qt6 widget files.

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by fn2006** [comment]
See https://github.com/PrismLauncher/PrismLauncher/issues/991, for the time being use either `pollymc` or `pollymc-qt5-bin` instead.

**Comment by spxcewolf** [comment]
Trying to build`pollymc`gives the following error:
```
[  4%] Building Java objects for NewLaunch.jar
warning: [options] bootstrap class path not set in conjunction with -source 7
error: Source option 7 is no longer supported. Use 8 or later.
error: Target option 7 is no longer supported. Use 8 or later.
make[2]: *** [libraries/launcher/CMakeFiles/NewLaunch.dir/build.make:96: libraries/launcher/CMakeFiles/NewLaunch.dir/java_compiled_NewLaunch] Error 2
make[1]: *** [CMakeFiles/Makefile2:1345: libraries/launcher/CMakeFiles/NewLaunch.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
```
I'm not sure if this is just a problem with Java while trying to build with it in a chroot environment.

**Comment by fn2006** [comment]
You need to use Java 17, Java 20 doesn't work.

**Comment by spxcewolf** [comment]
For some reason it seems to be downloading JDK20 even after choosing JDK17. Seems to be some other problem with my install environment.

**Comment by fn2006** [comment]
Have you tried using `archlinux-java` to set Java 17 as the default?

**Comment by spxcewolf** [comment]
I did, but Java was weirdly removed from the chroot after every error. I built it in a new chroot and it works now. Thanks.

**Comment by fn2006** [comment]
This is still an issue because `pollymc-bin` doesn't run, reopening this until it gets fixed upstream by Prism.
