### ISSUE TITLE
Request: Upgrade to Prism Launcher 7.1

### ISSUE THREAD

**Issue by lemonzest79** [fn2006/PollyMC#70]
### Role

I play modded minecraft

### Suggestion

Upgrade to Prism Launcher 7.1 Please

### Benefit

Updated to latest version of Prism Launcher

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by fn2006** [comment]
Sorry, I've not been on my computer much this week and didn't realise Prism 7.1 was out. I'll get on this ASAP.

**Comment by fn2006** [comment]
Done.
