### ISSUE TITLE
Frequent Crashes in Mod Downloader

### ISSUE THREAD

**Issue by LegendaryGW** [fn2006/PollyMC#71]
### Operating System

Windows 7 Ultimate

### Version of PollyMC

PollyMC 7.0 Legacy MSVC

### Version of Qt

Qt 5.15.2

### Description of bug

While scrolling through mods in the mod downloader menu (by clicking the "Download mods" in the Mods tab of the instance),
the launcher frequently crashes.
I have tested this on Prism Launcher (7.0 Legacy) and it doesn't seem to crash so this is specific to PollyMC

### Steps to reproduce

Click the 'Download mods' button in the Mods tab of the selected instance and scroll through the mods.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by LegendaryGW** [comment]
Switching between Modrinth and Curseforge during a search also causes it to crash frequently

(accidentaly closed the issue)

**Comment by fn2006** [comment]
I've not been experiencing this myself, please could you trigger the crash then upload the launcher's log file?
the log is called `PollyMC-0.log` and should be in `%AppData%\PollyMC` unless you're using a portable build.

**Comment by LegendaryGW** [comment]
[PollyMC-0.log](https://github.com/fn2006/PollyMC/files/11817442/PollyMC-0.log)

     0.000 D | Testing "F:/GAMES/PollyMC-Windows-MSVC-Legacy-Portable-7.0/qtlogging.ini" ...
     0.000 D | Loading logging rules from: "F:/GAMES/PollyMC-Windows-MSVC-Legacy-Portable-7.0/qtlogging.ini"
     0.000 D | Setting log rules:
     0.000 D |      "*.debug=true"
     0.000 D |      "launcher.auth.credentials.debug=false"
     0.000 D |      "launcher.task=false"
     0.000 D |      "launcher.task.net=true"
     0.000 D |      "launcher.task.net.download.debug=false"
     0.000 D |      "launcher.task.net.metacache=false"
     0.000 D |      "launcher.task.net.metacache.http=true"
     0.000 D |      "launcher.task.net.upload=true"
     0.000 D |      "qt.*.debug=false"
     0.000 D | <> Log initialized.
     0.000 D | <> No migration needed from "PolyMC"
     0.000 D | <> No migration needed from "MultiMC"
     0.000 D | "PollyMC" , (c) 2013-2021  "© 2022-2023 PollyMC Contributors\n© 2022-2023 Prism Launcher Contributors\n© 2021-2022 PolyMC Contributors \n© 2012-2021 MultiMC Contributors"
     0.000 D | Version                    :  "7.0"
     0.000 D | Git commit                 :  "392822ec7aab149e965842f2701d37b1ab643d3b"
     0.000 D | Git refspec                :  "refs/heads/stable"
     0.000 D | Work dir before adjustment :  "F:/GAMES/PollyMC-Windows-MSVC-Legacy-Portable-7.0"
     0.000 D | Work dir after adjustment  :  "F:/GAMES/PollyMC-Windows-MSVC-Legacy-Portable-7.0"
     0.000 D | Adjusted by                :  "Portable data path"
     0.000 D | Binary path                :  "F:/GAMES/PollyMC-Windows-MSVC-Legacy-Portable-7.0"
     0.000 D | Application root path      :  "F:/GAMES/PollyMC-Windows-MSVC-Legacy-Portable-7.0"
     0.000 D | <> Paths set.
     0.940 D | Detected default console font: "Courier" , substitutions: ""
     1.609 D | <> Settings loaded.
     3.004 D | Detecting proxy settings...
     3.063 D | Using no proxy is an option!
     3.064 D | <> Network done.
     3.756 D | Your language is "en_US"
     3.756 D | <> Translations loaded.
     4.023 D | Started watching  "F:/GAMES/PollyMC-Windows-MSVC-Legacy-Portable-7.0/icons"
     4.023 D | Adding  "icons/1200px-Benzene_200.svg.png"
     4.578 D | Adding  "icons/modrinth_thunder"
     4.850 D | Adding  "icons/modrinth_extreme-optimization!"
     4.886 D | Adding  "icons/2dxaFs9.jpg"
     5.262 D | Adding  "icons/modrinth_sop"
     5.488 D | Adding  "icons/curseforge_637712078711696255"
     5.602 D | Adding  "icons/modrinth_the-cloud-client-experience"
     5.666 D | Adding  "icons/cyclobutadiene02.png"
     5.701 D | Adding  "icons/Benzene_U+232C.jpg"
     5.740 D | Adding  "icons/modrinth_adrenaline"
     5.777 D | Sorting icon list...
     5.777 D | <> Instance icons intialized.
     5.801 D | [Theme] <> Icon themes initialized.
     5.801 D | [Theme] <> Initializing Widget Themes
     5.801 D | [Theme] Determining System Theme...
     5.801 D | [Theme] System theme seems to be: "windowsvista"
     5.801 D | [Theme] Considering theme from theme factory: "windowsvista"
     5.801 D | [Theme] System theme has been determined to be: "windowsvista"
     5.801 D | [Theme] Loading Built-in Theme: "system"
     5.801 D | [Theme] Loading Built-in Theme: "dark"
     5.801 D | [Theme] Loading Built-in Theme: "bright"
     5.801 D | [Theme] Theme Folder Path:  "F:/GAMES/PollyMC-Windows-MSVC-Legacy-Portable-7.0/themes"
     5.801 D | [Theme] <> Widget themes initialized.
     5.801 D | Instance path              :  "instances"
     5.801 D | Loading Instances...
     5.801 D | Discovering instances in "F:/GAMES/PollyMC-Windows-MSVC-Legacy-Portable-7.0/instances"
     5.864 D | Found instance ID "1.12.2"
     5.929 D | Found instance ID "1.8.nein"
     5.962 D | Found instance ID "Authenticity"
     5.994 D | Found instance ID "Compliance"
     6.047 D | Found instance ID "pointFIVE"
     6.115 D | Found instance ID "Ruby"
     6.177 D | Found instance ID "SleepySpecial"
     6.195 D | Found instance ID "Speed"
     6.227 D | Found instance ID "WAR"
     6.228 D | Will load group list now.
     6.229 D | Group list loaded.
     6.258 D | Loaded instance  "1.12.2 "  from  "F:/GAMES/PollyMC-Windows-MSVC-Legacy-Portable-7.0/instances/1.12.2"
     6.259 D | Loaded instance  "1.8.nein"  from  "F:/GAMES/PollyMC-Windows-MSVC-Legacy-Portable-7.0/instances/1.8.nein"
     6.285 D | Loaded instance  "Authenticity"  from  "F:/GAMES/PollyMC-Windows-MSVC-Legacy-Portable-7.0/instances/Authenticity"
     6.297 D | Loaded instance  "Compliance"  from  "F:/GAMES/PollyMC-Windows-MSVC-Legacy-Portable-7.0/instances/Compliance"
     6.322 D | Loaded instance  "pointFIVE"  from  "F:/GAMES/PollyMC-Windows-MSVC-Legacy-Portable-7.0/instances/pointFIVE"
     6.342 D | Loaded instance  "Ruby"  from  "F:/GAMES/PollyMC-Windows-MSVC-Legacy-Portable-7.0/instances/Ruby"
     6.354 D | Loaded instance  "SleepySpecial"  from  "F:/GAMES/PollyMC-Windows-MSVC-Legacy-Portable-7.0/instances/SleepySpecial"
     6.382 D | Loaded instance  "Speed"  from  "F:/GAMES/PollyMC-Windows-MSVC-Legacy-Portable-7.0/instances/Speed"
     6.410 D | Loaded instance  "WAR"  from  "F:/GAMES/PollyMC-Windows-MSVC-Legacy-Portable-7.0/instances/WAR"
     6.410 D | <> Instances loaded.
     6.410 D | Loading accounts...
     6.514 D | AccountList: Queued default account with internal ID  "b403ab9b99f44138ab224926520a6e59"  to refresh first
     6.515 D | AccountList: Queued account with internal ID  "37650211d72e46599290a964bbe53e1f"  to refresh
     6.621 D | AuthFlow: "Logging in with Ely.by account."
     6.982 D | RefreshSchedule: Processing account  "legendarygamewrecker@gmail.com"  with internal ID  "b403ab9b99f44138ab224926520a6e59"
     6.982 D | <> Accounts loaded.
     7.045 D | <> Cache initialized.
     7.045 D | Downloading Translations Index...
     7.065 W | [launcher.task.net]: [HttpMetaCache] Removing cache entry because of old age!
     7.077 D | [Theme] <> Icon theme set.
     7.077 D | [Theme] applying theme "Dark"
     7.126 D | [Theme] <> Application theme set.
     8.048 D | Reloading news.
     8.095 D | Loading components
     8.233 D | Component list save is scheduled for "1.12.2 "
     8.341 D | Resolving dependencies
     8.341 D | "Req: net.minecraft == 1.12.2" Is met.
     8.341 D | "Req: org.lwjgl" Is met.
     8.341 D | Component list update/resolve task succeeded for "1.12.2 "
     8.579 D | <> Main window shown.
     8.885 D | Dir changed: "F:/GAMES/PollyMC-Windows-MSVC-Legacy-Portable-7.0/translations"
     9.508 D | Got translations index!
     9.508 D | Dir changed: "F:/GAMES/PollyMC-Windows-MSVC-Legacy-Portable-7.0/translations"
     9.528 D | Dir changed: "F:/GAMES/PollyMC-Windows-MSVC-Legacy-Portable-7.0/translations"
     9.529 D | Dir changed: "F:/GAMES/PollyMC-Windows-MSVC-Legacy-Portable-7.0/translations"
     9.530 D | Dir changed: "F:/GAMES/PollyMC-Windows-MSVC-Legacy-Portable-7.0/translations"
     9.673 D | Finished loading RSS feed.
     9.722 D | Loaded news entry "Prism Launcher Release 7.1, now available"
     9.722 D | Loaded news entry "Prism Launcher Release 7.0, now available"
     9.722 D | Loaded news entry "FTB Modpack Downloading Removal."
     9.722 D | Loaded news entry "[MALWARE WARNING] \"fractureiser\" malware in many popular Minecraft mods and modpacks"
     9.722 D | Loaded news entry "Happy Pride Month!"
     9.722 D | Loaded news entry "[SECURITY UPDATE] Prism Launcher Release 6.3, now available"
     9.722 D | Loaded news entry "Prism Launcher Release 6.2, now available"
     9.722 D | Loaded news entry "Prism Launcher Release 6.1, now available"
     9.722 D | Loaded news entry "Prism Launcher Release 6.0, now available"
     9.723 D | Loaded news entry "Prism Launcher Release 5.2, now available"
     9.723 D | Loaded news entry "Prism Launcher Release 5.1, now available"
     9.723 D | Loaded news entry "Prism Launcher Release 5.0, now available"
     9.723 D | Loaded news entry "PolyMC Update 1.4.2, now available"
     9.723 D | Loaded news entry "PolyMC Update 1.4.1, now available"
     9.723 D | Loaded news entry "PolyMC Update 1.4.0, now available"
     9.723 D | Loaded news entry "PolyMC Update 1.3.2, now available"
     9.723 D | Loaded news entry "PolyMC Update 1.3.1, now available"
     9.723 D | Loaded news entry "PolyMC Update 1.3.0, now available"
     9.723 D | Loaded news entry "PolyMC Update 1.2.2, now available (CurseForge Hotfix)"
     9.723 D | Loaded news entry "PolyMC Update 1.2.1, now available"
     9.724 D | Loaded news entry "PolyMC Update 1.2.0, now available"
     9.724 D | Loaded news entry "PolyMC Update 1.1.1, now available"
     9.724 D | Loaded news entry "PolyMC Update 1.1.0, now available"
     9.724 D | Loaded news entry "Moving on"
     9.724 D | Loaded news entry "Modrinth support and Mod downloading"
     9.724 D | Loaded news entry "New maintainers and step down."
     9.724 D | News loading succeeded.
     9.861 D | Processing authentication response.
     9.861 D | Getting access token.
     9.861 D | Finished reading authentication response.
     9.861 D | AuthFlow: "Fetching the Minecraft profile."
    10.046 D | "{\"id\":\"a7b6fb9f15d34650a4b4a4efe7664b16\",\"name\":\"LegendaryGW\",\"properties\":[{\"name\":\"textures\",\"value\":\"eyJ0aW1lc3RhbXAiOjE2ODczNTAwNzUyNjksInByb2ZpbGVJZCI6ImE3YjZmYjlmMTVkMzQ2NTBhNGI0YTRlZmU3NjY0YjE2IiwicHJvZmlsZU5hbWUiOiJMZWdlbmRhcnlHVyIsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL2VseS5ieS9taW5lY3JhZnQvc2tpbnMvMWIxYTVlNjNmNGVjOTc4OTZjZmM1YzdiMWM0MTA1MTEucG5nIn19fQ==\"},{\"name\":\"ely\",\"value\":\"but why are you asking?\"}]}"
    10.097 D | Parsing Minecraft profile...
    10.097 D | AuthFlow: "Getting skin."
    10.531 D | Writing account list to "accounts.json"
    10.532 D | Building JSON data structure.
    10.532 D | Building account array.
    10.547 D | Writing account list to file.
    10.616 D | Saved account list to "accounts.json"
    10.617 D | RefreshSchedule: Background account refresh succeeded
    13.241 D | Component list save performed now for "1.12.2 "
    16.265 D | Loading components
    16.265 D | Index is already loaded
    16.322 D | Component list save is scheduled for "pointFIVE"
    16.376 D | Resolving dependencies
    16.376 D | "Req: net.minecraft == 1.16.5" Is met.
    16.376 D | "Req: org.lwjgl3" Is met.
    16.376 D | Component list update/resolve task succeeded for "pointFIVE"
    19.085 D | Component list save performed now for "pointFIVE"
    19.140 D | Loading components
    19.140 D | Index is already loaded
    19.140 D | Component list save is scheduled for "pointFIVE"
    19.141 D | Resolving dependencies
    19.141 D | "Req: net.minecraft == 1.16.5" Is met.
    19.141 D | "Req: org.lwjgl3" Is met.
    19.141 D | Component list update/resolve task succeeded for "pointFIVE"
    19.152 W | [launcher.task.net]: [HttpMetaCache] Removing cache entry because of old age!
    19.183 D | QProxyStyle NoBigComboBox created for "" QStyleSheetStyle(0x493c30)
    19.473 D | Instance-type specific settings were loaded!
    21.543 D | Applying "org.lwjgl3" GOOD
    21.543 D | Applying "net.minecraft" GOOD
    21.543 D | Applying "net.minecraftforge" GOOD
    22.573 D | Started watching  "F:/GAMES/PollyMC-Windows-MSVC-Legacy-Portable-7.0/instances/pointFIVE/.minecraft/mods"
    22.574 D | Started watching  "F:/GAMES/PollyMC-Windows-MSVC-Legacy-Portable-7.0/instances/pointFIVE/.minecraft/mods/.index"
    24.144 D | Component list save performed now for "pointFIVE"
    30.943 D | AuthFlow: "Creating offline account."
    30.943 D | Writing account list to "accounts.json"
    30.943 D | Building JSON data structure.
    30.943 D | Building account array.
    30.943 D | Writing account list to file.
    30.994 D | Saved account list to "accounts.json"
    30.995 D | RefreshSchedule: Background account refresh succeeded
    30.995 D | RefreshSchedule: Processing account  "<Offline>"  with internal ID  "37650211d72e46599290a964bbe53e1f"
    39.321 W | [launcher.task.net]: [HttpMetaCache] Removing cache entry because of old age!
    42.717 W | libpng warning: sRGB: cHRM chunk does not match sRGB
    51.261 W | libpng warning: iCCP: known incorrect sRGB profile
    59.542 C | [launcher.task.net.download]: "{604017a5-6338-4aeb-885c-edb947351041}" Failed  ""  with reason  QNetworkReply::ProtocolUnknownError
    60.791 C | [launcher.task.net.download]: "{604017a5-6338-4aeb-885c-edb947351041}" Failed  ""  with reason  QNetworkReply::ProtocolUnknownError
    60.940 C | [launcher.task.net.download]: "{604017a5-6338-4aeb-885c-edb947351041}" Failed  ""  with reason  QNetworkReply::ProtocolUnknownError
    63.609 W | [launcher.task.net]: [HttpMetaCache] Removing cache entry because of old age!
    68.840 W | libpng warning: sRGB: cHRM chunk does not match sRGB

**Comment by LegendaryGW** [comment]
Yes, I just tested again on Prism Launcher 7.1 and it doesn't crash

**Comment by fn2006** [comment]
Very strange, I'll look into this.
