### ISSUE TITLE
Name of the Project

### ISSUE THREAD

**Issue by ripsivis** [fn2006/PollyMC#73]
### Role

I play Minecraft.

### Suggestion

fn2006 should change the name of the project.

### Benefit

It's been months since the polymc incident but name of the project still confuses people, making them think this is either polymc or fork of that insecure(?) code.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by fn2006** [comment]
This was already discussed in https://github.com/fn2006/PollyMC/issues/29 and my opinion on the name hasn't changed much.
I admit the name is confusing due to how similar it is to PolyMC but I'm fond of the name and changing it would cause even more confusion.
