### ISSUE TITLE
Unable to add Microsoft account

### ISSUE THREAD

**Issue by Delyfsss** [fn2006/PollyMC#75]
### Operating System

Windows, Linux

### Version of PollyMC

PollyMC 7.1

### Version of Qt

Qt 6.5.1

### Description of bug

Unable to add Microsoft account
![image](https://github.com/fn2006/PollyMC/assets/106402376/748053df-a4ef-4756-bec9-bc39902f8a02)

### Steps to reproduce

Open "Manage Accounts"

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by RpMGrut** [comment]
Yes, I have the same problem.

![image](https://github.com/fn2006/PollyMC/assets/128047676/77d0731f-24ab-4560-8107-23b08f86a94b)
