### ISSUE TITLE
Trojan detected by VirusTotal

### ISSUE THREAD

**Issue by herfdiug** [fn2006/PollyMC#78]
### Goal

https://i.imgur.com/BIMbbck.png

I scanned the PollyMC-Windows-MinGW-w64-7.1.zip file onto virus total and it apparently detected a trojan, can someone explain to me if this is a false positive or not? I'd appreciate the help, thanks

### Motivation

Trojan is a virus therefore I wanted clarification if the detected trojan is a false positive or not

### Specification

I have no idea what to write here

### Drawbacks

It might be a false positive

### Unresolved Questions

No idea what to write here

### Alternatives Considered

Maybe it's a false positive

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by fn2006** [comment]
It's a false positive, Prism Launcher's MinGW builds trigger the security vendor: https://www.virustotal.com/gui/file/e1b0d7855bd955a2cc6612d33fcdd76139876e6336ea3c179be13cc153756514
