### ISSUE TITLE
Ely.by launch is immensely slow

### ISSUE THREAD

**Issue by 4310V343k** [fn2006/PollyMC#80]
### Operating System

Windows

### Version of PollyMC

PollyMC 7.1

### Version of Qt

Qt 6.5.1

### Description of bug

When trying to launch minecraft with an ely.by account it takes from very long time to launch to not launching at all.
When i switch to an MS account the launch stops at "downloading assets", if I stop it and launch the game again it opens immediately.

### Steps to reproduce

* add an ely.by account
* launch a modpack

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by fn2006** [comment]
This is still an issue.

**Comment by fn2006** [comment]
Should be fixed as a side effect of the rewritten authlib-injector support.
