### ISSUE TITLE
Make it clear how and how not to get support with the launcher

### ISSUE THREAD

**Issue by LennyMcLennington** [fn2006/PollyMC#81]
### Role

I keep getting people in the PolyMC discord asking for support with PollyMC

### Suggestion

title

### Benefit

People will be able to get help more easily instead of going to the wrong place.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Make it clear that PollyMC is not the same as PolyMC, and that support is done through GitHub issues and discussions, not the PolyMC Discord server.

Maybe have a header called "Support" so people who want support know they need to read that section. Example:

# Support
The only way to get support with PollyMC is through the GitHub Issues or Discussions on this repo. Please do not bother the PolyMC or Prism Launcher communities as they will be unable to assist you.

**Comment by ktheticdev** [comment]
this is hilarious

**Comment by fn2006** [comment]
Fixed.
Sorry about not getting to this sooner, hadn't checked my github notifications in a while.
