### ISSUE TITLE
Nix packages are broken

### ISSUE THREAD

**Issue by Mr-Andersen** [fn2006/PollyMC#85]
### Operating System

Linux

### Version of PollyMC

commit: bae038846c11c6d2a068fe3623c61aee6fb5d521

### Version of Qt

Qt from nixpkgs pinned in the flake

### Description of bug

```
> nix run github:fn2006/PollyMC
error: attribute 'pollymc' missing

       at /nix/store/dvk3n9zswygccw5c8592yjb4inwahqy9-source/nix/distribution.nix:26:17:

           25|       pollymc-unwrapped = mkPrism final.qt6Packages;
           26|       pollymc = prev.pollymc.override {inherit (final) pollymc-unwrapped;};
             |                 ^
           27|     };
       Did you mean one of polymc or polyml?
(use '--show-trace' to show detailed location information)
```

### Steps to reproduce

Run `nix run github:fn2006/PollyMC` in shell

### Suspected cause

Maybe it should be `pollymc = prev.prismlauncher.override {inherit (final) prismlauncher-unwrapped;};`?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Mr-Andersen** [comment]
I would submit a PR if I knew what code is supposed to be there :) but I can't be sure

**Comment by I-like-stuff** [comment]
is there a workaround for this ?? I seem to get this error when I try to install it using flakes

**Comment by I-like-stuff** [comment]
have there been updates about it
