### ISSUE TITLE
New version of Prism out, version 7.2

### ISSUE THREAD

**Issue by lemonzest79** [fn2006/PollyMC#87]
### Role

I Play Modded Minecraft

### Suggestion

Prism has updated to version 7.2, please update PollyMC

### Benefit

Newer version

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

https://github.com/PrismLauncher/PrismLauncher/releases

**Comment by fn2006** [comment]
Updated.

**Comment by lemonzest79** [comment]
Thank you :)
