### ISSUE TITLE
Cannot download index.json

### ISSUE THREAD

**Issue by stutsanks** [fn2006/PollyMC#9]
### Operating System

Windows

### Version of PollyMC

Windows-Legacy-PollyMC-1.4.0

### Description of bug

When clicking on new instance, it shows an error where it cant download index.json. Even when clicking on modrinth, it says cant find modpacks due to network issue.

### Steps to reproduce

Open pollymc and click new instance for first error
then modrinth for second error.

### Suspected cause

It could be that i have only support for tls, Please do add tls support for 32 bit

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by stutsanks** [comment]
Im on windows 7 32 bit.

**Comment by stutsanks** [comment]
Accident

**Comment by stutsanks** [comment]
The index.json thing is a client side issue? But the launcher doesnt have tls support as to the 64 bit launcher. Also another issue is that when i try putting mcpack in the pollymc, it crashes, Also i have an old pc but still runs minecraft with modpacks

**Comment by fn2006** [comment]
Since it works fine on my old laptop that runs Windows 7 32-Bit I think the issue is the way your computer is setup, do you have problems like this with other programs?

**Comment by stutsanks** [comment]
Yes, on every fork of multimc i get these kinds of error. But 6 months back, my pc was running these smoothly without error. Now my only option is to extract the modpack i use and put it on sk launcher(launchers like this is supported by my pc, like the original launcher) and play.

**Comment by fn2006** [comment]
Ok, I have a feeling you have outdated SSL certs, can you try running windows update?

**Comment by stutsanks** [comment]
Thats the problem, i have outdated ssl certs and i dont know how to update them

**Comment by fn2006** [comment]
Uhh shit, I had the same problem on my old laptop last year but I forgot how I fixed it, I'll try to figure out what I did and then I'll post how to fix it.

**Comment by stutsanks** [comment]
Thanks, right now windows update on my pc is running forever, so i will completely depend on you for this situation

**Comment by fn2006** [comment]
Alright, try installing this update: https://www.microsoft.com/en-sg/download/details.aspx?id=45588

**Comment by stutsanks** [comment]
THANK YOU SO MUCH FOR YOUR TIME AND RESEARCH. IT HAS FIXED MY ERROR. But don't get too happy, it did'nt work on your launcher, it worked on other forks of multimc. so, you lost one user.

**Comment by fn2006** [comment]
Glad it worked, don't forget to run windows update, you're probably missing 100s of security updates.

**Comment by stutsanks** [comment]
just an update. I fixed the index.json and other error by security update. thanks for your advice. I cannot thank you enough what this conversation did to me. THANK YOU
