### ISSUE TITLE
all instances with fabric crash before launching

### ISSUE THREAD

**Issue by lueman** [fn2006/PollyMC#95]
### Operating System

Windows 10

### Version of PollyMC

Pollymc 6.3

### Version of Qt

Qt 6.42

### Description of bug

any minecraft instance that uses fabric crashes before it reaches the loading screen

### Steps to reproduce

here is a crash log for an instance running minecraft 1.20.1 and fabric 0.14.22 with no mods, installed using the launcher
https://mclo.gs/72WHNED

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Darthagnon** [comment]
I used the Qt5 on Win10 build with Fabric and a few mods and it works fine, though notably Minecraft 1.18 was what I was playing. I've seen Qt6 cause more problems than it solves.

**Comment by lueman** [comment]
how do you change the qt version then?

**Comment by lueman** [comment]
nvm i'm a dummy who forgot to update
